[package]
name = "oxpdf-cli"
version = "1.0.1"
edition = "2021"
authors = ["isaim0011 <https://github.com/isaim0011>"]
description = "High-performance command-line interface for the oxpdf PDF engine"
license = "MIT OR Apache-2.0"

[[bin]]
name = "oxpdf"
path = "src/main.rs"

[dependencies]
oxpdf = { path = "..", version = "1.0.1" }
